<?php

    $name= ["Bulbasaur","Ivysaur","Venusaur","Charmander","Charmeleon","Charizard","Squirtle","Wartortle","Blastoise","Caterpie","Metapod","Butterfree",
        "Weedle","Kakuna","Beedrill","Pidgey","Pidgeotto","Pidgeot","Rattata","Raticate","Spearow","Fearow","Ekans","Arbok","Pikachu","Raichu","Sandshrew",
        "Sandslash","Nidoran♀","Nidorina","Nidoqueen","Nidoran♂","Nidorino","Nidoking","Clefairy","Clefable","Vulpix","Ninetales","Jigglypuff","Wigglytuff",
        "Zubat","Golbat","Oddish","Gloom","Vileplume","Paras","Parasect","Venonat","Venomoth","Diglett","Dugtrio","Meowth","Persian","Psyduck","Golduck","Mankey",
        "Primeape","Growlithe","Arcanine","Poliwag","Poliwhirl","Poliwrath","Abra","Kadabra","Alakazam","Machop","Machoke","Machamp","Bellsprout","Weepinbell","Victreebel",
        "Tentacool","Tentacruel","Geodude","Graveler","Golem","Ponyta","Rapidash","Slowpoke","Slowbro","Magnemite","Magneton","Farfetch'd","Doduo","Dodrio","Seel","Dewgong",
        "Grimer","Muk","Shellder","Cloyster","Gastly","Haunter","Gengar","Onix","Drowzee","Hypno","Krabby","Kingler","Voltorb","Electrode","Exeggcute","Exeggutor","Cubone",
        "Marowak","Hitmonlee","Hitmonchan","Lickitung","Koffing","Weezing","Rhyhorn","Rhydon","Chansey","Tangela","Kangaskhan","Horsea","Seadra","Goldeen","Seaking","Staryu",
        "Starmie","Mr.Mime","Scyther","Jynx","Electabuzz","Magmar","Pinsir","Tauros","Magikarp","Gyarados","Lapras","Ditto","Eevee","Vaporeon","Jolteon","Flareon","Porygon",
        "Omanyte","Omastar","Kabuto","Kabutops","Aerodactyl","Snorlax","Articuno","Zapdos","Moltres","Dratini","Dragonair","Dragonite","Mewtwo","Mew","Chikorita","Bayleef",
        "Meganium","Cyndaquil","Quilava","Typhlosion","Totodile","Croconaw","Feraligatr","Sentret","Furret","Hoothoot","Noctowl","Ledyba","Ledian","Spinarak","Ariados",
        "Crobat","Chinchou","Lanturn","Pichu","Cleffa","Igglybuff","Togepi","Togetic","Natu","Xatu","Mareep","Flaaffy","Ampharos","Bellossom","Marill","Azumarill","Sudowoodo",
        "Politoed","Hoppip","Skiploom","Jumpluff","Aipom","Sunkern","Sunflora","Yanma","Wooper","Quagsire","Espeon","Umbreon","Murkrow","Slowking","Misdreavus","Unown",
        "Wobbuffet","Girafarig","Pineco","Forretress","Dunsparce","Gligar","Steelix","Snubbull","Granbull","Qwilfish","Scizor","Shuckle","Heracross","Sneasel","Teddiursa",
        "Ursaring","Slugma","Magcargo","Swinub","Piloswine","Corsola","Remoraid","Octillery","Delibird","Mantine","Skarmory","Houndour","Houndoom","Kingdra","Phanpy","Donphan",
        "Porygon2","Stantler","Smeargle","Tyrogue","Hitmontop","Smoochum","Elekid","Magby","Miltank","Blissey","Raikou","Entei","Suicune","Larvitar","Pupitar","Tyranitar",
        "Lugia","Ho-Oh","Celebi","Treecko","Grovyle","Sceptile","Torchic","Combusken","Blaziken","Mudkip","Marshtomp","Swampert","Poochyena","Mightyena","Zigzagoon","Linoone",
        "Wurmple","Silcoon","Beautifly","Cascoon","Dustox","Lotad","Lombre","Ludicolo","Seedot","Nuzleaf","Shiftry","Taillow","Swellow","Wingull","Pelipper","Ralts","Kirlia",
        "Gardevoir","Surskit","Masquerain","Shroomish","Breloom","Slakoth","Vigoroth","Slaking","Nincada","Ninjask","Shedinja","Whismur","Loudred","Exploud","Makuhita",
        "Hariyama","Azurill","Nosepass","Skitty","Delcatty","Sableye","Mawile","Aron","Lairon","Aggron","Meditite","Medicham","Electrike","Manectric","Plusle","Minun",
        "Volbeat","Illumise","Roselia","Gulpin","Swalot","Carvanha","Sharpedo","Wailmer","Wailord","Numel","Camerupt","Torkoal","Spoink","Grumpig","Spinda","Trapinch",
        "Vibrava","Flygon","Cacnea","Cacturne","Swablu","Altaria","Zangoose","Seviper","Lunatone","Solrock","Barboach","Whiscash","Corphish","Crawdaunt","Baltoy","Claydol",
        "Lileep","Cradily","Anorith","Armaldo","Feebas","Milotic","Castform","Kecleon","Shuppet","Banette","Duskull","Dusclops","Tropius","Chimecho","Absol","Wynaut",
        "Snorunt","Glalie","Spheal","Sealeo","Walrein","Clamperl","Huntail","Gorebyss","Relicanth","Luvdisc","Bagon","Shelgon","Salamence","Beldum","Metang","Metagross",
        "Regirock","Regice","Registeel","Latias","Latios","Kyogre","Groudon","Rayquaza","Jirachi","Deoxys","Turtwig","Grotle","Torterra","Chimchar","Monferno","Infernape",
        "Piplup","Prinplup","Empoleon","Starly","Staravia","Staraptor","Bidoof","Bibarel","Kricketot","Kricketune","Shinx","Luxio","Luxray","Budew","Roserade","Cranidos",
        "Rampardos","Shieldon","Bastiodon","Burmy","Wormadam","Mothim","Combee","Vespiquen","Pachirisu","Buizel","Floatzel","Cherubi","Cherrim","Shellos","Gastrodon",
        "Ambipom","Drifloon","Drifblim","Buneary","Lopunny","Mismagius","Honchkrow","Glameow","Purugly","Chingling","Stunky","Skuntank","Bronzor","Bronzong","Bonsly",
        "Mime Jr.","Happiny","Chatot","Spiritomb","Gible","Gabite","Garchomp","Munchlax","Riolu","Lucario","Hippopotas","Hippowdon","Skorupi","Drapion","Croagunk","Toxicroak",
        "Carnivine","Finneon","Lumineon","Mantyke","Snover","Abomasnow","Weavile","Magnezone","Lickilicky","Rhyperior","Tangrowth","Electivire","Magmortar","Togekiss",
        "Yanmega","Leafeon","Glaceon","Gliscor","Mamoswine","Porygon-Z","Gallade","Probopass","Dusknoir","Froslass","Rotom","Uxie","Mesprit","Azelf","Dialga","Palkia",
        "Heatran","Regigigas","Giratina","Cresselia","Phione","Manaphy","Darkrai","Shaymin","Arceus","Snivy","Servine","Serperior","Tepig","Pignite","Emboar","Oshawott",
        "Dewott","Samurott","Patrat","Watchog","Lillipup","Herdier","Stoutland","Purrloin","Liepard","Pansage","Simisage","Pansear","Simisear","Panpour","Simipour","Munna",
        "Musharna","Pidove","Tranquill","Unfezant","Blitzle","Zebstrika","Roggenrola","Boldore","Gigalith","Woobat","Swoobat","Drilbur","Excadrill","Audino","Timburr",
        "Gurdurr","Conkeldurr","Tympole","Palpitoad","Seismitoad","Throh","Sawk","Sewaddle","Swadloon","Leavanny","Venipede","Whirlipede","Scolipede","Cottonee","Whimsicott",
        "Petilil","Lilligant","Basculin","Sandile","Krokorok","Krookodile","Darumaka","Darmanitan","Maractus","Dwebble","Crustle","Scraggy","Scrafty","Sigilyph","Yamask",
        "Cofagrigus","Tirtouga","Carracosta","Archen","Archeops","Trubbish","Garbodor","Zorua","Zoroark","Minccino","Cinccino","Gothita","Gothorita","Gothitelle","Solosis",
        "Duosion","Reuniclus","Ducklett","Swanna","Vanillite","Vanillish","Vanilluxe","Deerling","Sawsbuck","Emolga","Karrablast","Escavalier","Foongus","Amoonguss",
        "Frillish","Jellicent","Alomomola","Joltik","Galvantula","Ferroseed","Ferrothorn","Klink","Klang","Klinklang","Tynamo","Eelektrik","Eelektross","Elgyem","Beheeyem",
        "Litwick","Lampent","Chandelure","Axew","Fraxure","Haxorus","Cubchoo","Beartic","Cryogonal","Shelmet","Accelgor","Stunfisk","Mienfoo","Mienshao","Druddigon",
        "Golett","Golurk","Pawniard","Bisharp","Bouffalant","Rufflet","Braviary","Vullaby","Mandibuzz","Heatmor","Durant","Deino","Zweilous","Hydreigon","Larvesta",
        "Volcarona","Cobalion","Terrakion","Virizion","Tornadus","Thundurus","Reshiram","Zekrom","Landorus","Kyurem","Keldeo","Meloetta","Genesect","Chespin","Quilladin",
        "Chesnaught","Fennekin","Braixen","Delphox","Froakie","Frogadier","Greninja","Bunnelby","Diggersby","Fletchling","Fletchinder","Talonflame","Scatterbug","Spewpa",
        "Vivillon","Litleo","Pyroar","Flabébé","Floette","Florges","Skiddo","Gogoat","Pancham","Pangoro","Furfrou","Espurr","Meowstic","Honedge","Doublade","Aegislash",
        "Spritzee","Aromatisse","Swirlix","Slurpuff","Inkay","Malamar","Binacle","Barbaracle","Skrelp","Dragalge","Clauncher","Clawitzer","Helioptile","Heliolisk","Tyrunt",
        "Tyrantrum","Amaura","Aurorus","Sylveon","Hawlucha","Dedenne","Carbink","Goomy","Sliggoo","Goodra","Klefki","Phantump","Trevenant","Pumpkaboo","Gourgeist",
        "Bergmite","Avalugg","Noibat","Noivern","Xerneas","Yveltal","Zygarde","Diancie","Hoopa","Volcanion","Rowlet","Dartrix","Decidueye","Litten","Torracat","Incineroar",
        "Popplio","Brionne","Primarina","Pikipek","Trumbeak","Toucannon","Yungoos","Gumshoos","Grubbin","Charjabug","Vikavolt","Crabrawler","Crabominable","Oricorio",
        "Cutiefly","Ribombee","Rockruff","Lycanroc","Wishiwashi","Mareanie","Toxapex","Mudbray","Mudsdale","Dewpider","Araquanid","Fomantis","Lurantis","Morelull",
        "Shiinotic","Salandit","Salazzle","Stufful","Bewear","Bounsweet","Steenee","Tsareena","Comfey","Oranguru","Passimian","Wimpod","Golisopod","Sandygast","Palossand",
        "Pyukumuku","Código Cero","Silvally","Minior","Komala","Turtonator","Togedemaru","Mimikyu","Bruxish","Drampa","Dhelmise","Jangmo-o","Hakamo-o","Kommo-o",
        "Tapu Koko","Tapu Lele","Tapu Bulu","TapuFini","Cosmog","Cosmoem","Solgaleo","Lunala","Nihilego","Buzzwole","Pheromosa","Xurkitree","Celesteela","Kartana",
        "Guzzlord","Necrozma","Magearna","Marshado","Poipole","Naganadel","Stakataka","Blacephalon","Zeraora","Meltan","Melmetal","Basculin raya blanca","Grookey",
        "Thwackey","Rillaboom","Scorbunny","Raboot","Cinderace","Sobble","Drizzile","Inteleon","Skwovet","Greedent","Rookidee","Corvisquire","Corviknight","Blipbug",
        "Dottler","Orbeetle","Nickit","Thievul","Gossifleur","Eldegoss","Wooloo","Dubwool","Chewtle","Drednaw","Yamper","Boltund","Rolycoly","Carkol","Coalossal","Applin",
        "Flapple","Appletun","Silicobra","Sandaconda","Cramorant","Arrokuda","Barraskewda","Toxel","Toxtricity","Sizzlipede","Centiskorch","Clobbopus","Grapploct",
        "Sinistea","Polteageist","Hatenna","Hattrem","Hatterene","Impidimp","Morgrem","Grimmsnarl","Obstagoon","Perrserker","Cursola","Sirfetch'd","Mr. Rime","Runerigus",
        "Milcery","Alcremie","Falinks","Pincurchin","Snom","Frosmoth","Stonjourner","Eiscue","Indeedee","Morpeko","Cufant","Copperajah","Dracozolt","Arctozolt","Dracovish",
        "Arctovish","Duraludon","Dreepy","Drakloak","Dragapult","Zacian","Zacian","Zamazenta","Zamazenta","Eternatus","Kubfu","Urshifu","Zarude","Regieleki","Regidrago",
        "Glastrier","Spectrier","Calyrex","Calyrex Jinete Glacial","Calyrex Jinete Espectral","Wyrdeer","Kleavor","Basculegion"];

        $tipo1=["Planta","Planta","Planta","Fuego","Fuego","Fuego","Agua","Agua","Agua","Bicho","Bicho","Bicho","Bicho","Bicho","Bicho","Normal","Normal","Normal","Normal",
            "Normal","Normal","Normal","Veneno","Veneno","Eléctrico","Eléctrico","Tierra","Tierra","Veneno","Veneno","Veneno","Veneno","Veneno","Veneno","Hada","Hada",
            "Fuego","Fuego","Normal","Normal","Veneno","Veneno","Planta","Planta","Planta","Bicho","Bicho","Bicho","Bicho","Tierra","Tierra","Normal","Normal","Agua",
            "Agua","Lucha","Lucha","Fuego","Fuego","Agua","Agua","Agua","Psíquico","Psíquico","Psíquico","Lucha","Lucha","Lucha","Planta","Planta","Planta","Agua","Agua",
            "Roca","Roca","Roca","Fuego","Fuego","Agua","Agua","Eléctrico","Eléctrico","Normal","Normal","Normal","Agua","Agua","Veneno","Veneno","Agua","Agua","Fantasma",
            "Fantasma","Fantasma","Roca","Psíquico","Psíquico","Agua","Agua","Eléctrico","Eléctrico","Planta","Planta","Tierra","Tierra","Lucha","Lucha","Normal","Veneno",
            "Veneno","Tierra","Tierra","Normal","Planta","Normal","Agua","Agua","Agua","Agua","Agua","Agua","Psíquico","Bicho","Hielo","Eléctrico","Fuego","Bicho","Normal",
            "Agua","Agua","Agua","Normal","Normal","Agua","Eléctrico","Fuego","Normal","Roca","Roca","Roca","Roca","Roca","Normal","Hielo","Eléctrico","Fuego","Dragón",
            "Dragón","Dragón","Psíquico","Psíquico","Planta","Planta","Planta","Fuego","Fuego","Fuego","Agua","Agua","Agua","Normal","Normal","Normal","Normal","Bicho",
            "Bicho","Bicho","Bicho","Veneno","Agua","Agua","Eléctrico","Hada","Normal","Hada","Hada","Psíquico","Psíquico","Eléctrico","Eléctrico","Eléctrico","Planta",
            "Agua","Agua","Roca","Agua","Planta","Planta","Planta","Normal","Planta","Planta","Bicho","Agua","Agua","Psíquico","Siniestro","Siniestro","Agua","Fantasma",
            "Psíquico","Psíquico","Normal","Bicho","Bicho","Normal","Tierra","Acero","Hada","Hada","Agua","Bicho","Bicho","Bicho","Siniestro","Normal","Normal","Fuego",
            "Fuego","Hielo","Hielo","Agua","Agua","Agua","Hielo","Agua","Acero","Siniestro","Siniestro","Agua","Tierra","Tierra","Normal","Normal","Normal","Lucha","Lucha",
            "Hielo","Eléctrico","Fuego","Normal","Normal","Eléctrico","Fuego","Agua","Roca","Roca","Roca","Psíquico","Fuego","Psíquico","Planta","Planta","Planta","Fuego",
            "Fuego","Fuego","Agua","Agua","Agua","Siniestro","Siniestro","Normal","Normal","Bicho","Bicho","Bicho","Bicho","Bicho","Agua","Agua","Agua","Planta","Planta",
            "Planta","Normal","Normal","Agua","Agua","Psíquico","Psíquico","Psíquico","Bicho","Bicho","Planta","Planta","Normal","Normal","Normal","Bicho","Bicho","Bicho",
            "Normal","Normal","Normal","Lucha","Lucha","Normal","Roca","Normal","Normal","Siniestro","Acero","Acero","Acero","Acero","Lucha","Lucha","Eléctrico","Eléctrico",
            "Eléctrico","Eléctrico","Bicho","Bicho","Planta","Veneno","Veneno","Agua","Agua","Agua","Agua","Fuego","Fuego","Fuego","Psíquico","Psíquico","Normal","Tierra",
            "Tierra","Tierra","Planta","Planta","Normal","Dragón","Normal","Veneno","Roca","Roca","Agua","Agua","Agua","Agua","Tierra","Tierra","Roca","Roca","Roca","Roca",
            "Agua","Agua","Normal","Normal","Fantasma","Fantasma","Fantasma","Fantasma","Planta","Psíquico","Siniestro","Psíquico","Hielo","Hielo","Hielo","Hielo","Hielo",
            "Agua","Agua","Agua","Agua","Agua","Dragón","Dragón","Dragón","Acero","Acero","Acero","Roca","Hielo","Acero","Dragón","Dragón","Agua","Tierra","Dragón","Acero",
            "Psíquico","Planta","Planta","Planta","Fuego","Fuego","Fuego","Agua","Agua","Agua","Normal","Normal","Normal","Normal","Normal","Bicho","Bicho","Eléctrico","
            Eléctrico","Eléctrico","Planta","Planta","Roca","Roca","Roca","Roca","Bicho","Bicho","Bicho","Bicho","Bicho","Eléctrico","Agua","Agua","Planta","Planta","Agua",
            "Agua","Normal","Fantasma","Fantasma","Normal","Normal","Fantasma","Siniestro","Normal","Normal","Psíquico","Veneno","Veneno","Acero","Acero","Roca","Psíquico",
            "Normal","Normal","Fantasma","Dragón","Dragón","Dragón","Normal","Lucha","Lucha","Tierra","Tierra","Veneno","Veneno","Veneno","Veneno","Planta","Agua","Agua",
            "Agua","Planta","Planta","Siniestro","Eléctrico","Normal","Tierra","Planta","Eléctrico","Fuego","Hada","Bicho","Planta","Hielo","Tierra","Hielo","Normal",
            "Psíquico","Roca","Fantasma","Hielo","Eléctrico","Psíquico","Psíquico","Psíquico","Acero","Agua","Fuego","Normal","Fantasma","Psíquico","Agua","Agua","Siniestro",
            "Planta","Normal","Planta","Planta","Planta","Fuego","Fuego","Fuego","Agua","Agua","Agua","Normal","Normal","Normal","Normal","Normal","Siniestro","Siniestro",
            "Planta","Planta","Fuego","Fuego","Agua","Agua","Psíquico","Psíquico","Normal","Normal","Normal","Eléctrico","Eléctrico","Roca","Roca","Roca","Psíquico","Psíquico",
            "Tierra","Tierra","Normal","Lucha","Lucha","Lucha","Agua","Agua","Agua","Lucha","Lucha","Bicho","Bicho","Bicho","Bicho","Bicho","Bicho","Planta","Planta","Planta",
            "Planta","Agua","Tierra","Tierra","Tierra","Fuego","Fuego","Planta","Bicho","Bicho","Siniestro","Siniestro","Psíquico","Fantasma","Fantasma","Agua","Agua","Roca",
            "Roca","Veneno","Veneno","Siniestro","Siniestro","Normal","Normal","Psíquico","Psíquico","Psíquico","Psíquico","Psíquico","Psíquico","Agua","Agua","Hielo","Hielo",
            "Hielo","Normal","Normal","Eléctrico","Bicho","Bicho","Planta","Planta","Agua","Agua","Agua","Bicho","Bicho","Planta","Planta","Acero","Acero","Acero","Eléctrico",
            "Eléctrico","Eléctrico","Psíquico","Psíquico","Fantasma","Fantasma","Fantasma","Dragón","Dragón","Dragón","Hielo","Hielo","Hielo","Bicho","Bicho","Tierra","Lucha",
            "Lucha","Dragón","Tierra","Tierra","Siniestro","Siniestro","Normal","Normal","Normal","Siniestro","Siniestro","Fuego","Bicho","Siniestro","Siniestro","Siniestro",
            "Bicho","Bicho","Acero","Roca","Planta","Volador","Eléctrico","Dragón","Dragón","Tierra","Dragón","Agua","Normal","Bicho","Planta","Planta","Planta","Fuego",
            "Fuego","Fuego","Agua","Agua","Agua","Normal","Normal","Normal","Fuego","Fuego","Bicho","Bicho","Bicho","Fuego","Fuego","Hada","Hada","Hada","Planta","Planta",
            "Lucha","Lucha","Normal","Psíquico","Psíquico","Acero","Acero","Acero","Hada","Hada","Hada","Hada","Siniestro","Siniestro","Roca","Roca","Veneno","Veneno","Agua",
            "Agua","Eléctrico","Eléctrico","Roca","Roca","Roca","Roca","Hada","Lucha","Eléctrico","Roca","Dragón","Dragón","Dragón","Acero","Fantasma","Fantasma","Fantasma",
            "Fantasma","Hielo","Hielo","Volador","Volador","Hada","Siniestro","Dragón","Roca","Psíquico","Fuego","Planta","Planta","Planta","Fuego","Fuego","Fuego","Agua",
            "Agua","Agua","Normal","Normal","Normal","Normal","Normal","Bicho","Bicho","Bicho","Lucha","Lucha","Fuego","Bicho","Bicho","Roca","Roca","Agua","Veneno","Veneno",
            "Tierra","Tierra","Agua","Agua","Planta","Planta","Planta","Planta","Veneno","Veneno","Normal","Normal","Planta","Planta","Planta","Hada","Normal","Lucha","Bicho",
            "Bicho","Fantasma","Fantasma","Agua","Normal","Normal","Roca","Normal","Fuego","Eléctrico","Fantasma","Agua","Normal","Fantasma","Dragón","Dragón","Dragón",
            "Eléctrico","Psíquico","Planta","Agua","Psíquico","Psíquico","Psíquico","Psíquico","Roca","Bicho","Bicho","Eléctrico","Acero","Planta","Siniestro","Psíquico",
            "Acero","Lucha","Veneno","Veneno","Roca","Fuego","Eléctrico","Acero","Acero","Agua","Planta","Planta","Planta","Fuego","Fuego","Fuego","Agua","Agua","Agua",
            "Normal","Normal","Volador","Volador","Volador","Bicho","Bicho","Bicho","Siniestro","Siniestro","Planta","Planta","Normal","Normal","Agua","Agua","Eléctrico",
            "Eléctrico","Roca","Roca","Roca","Planta","Planta","Planta","Tierra","Tierra","Volador","Agua","Agua","Eléctrico","Eléctrico","Fuego","Fuego","Lucha","Lucha",
            "Fantasma","Fantasma","Psíquico","Psíquico","Psíquico","Siniestro","Siniestro","Siniestro","Siniestro","Acero","Fantasma","Lucha","Hielo","Tierra","Hada","Hada",
            "Lucha","Eléctrico","Hielo","Hielo","Roca","Hielo","Psíquico","Eléctrico","Acero","Acero","Eléctrico","Eléctrico","Agua","Agua","Acero","Dragón","Dragón","Dragón",
            "Hada","Hada","Lucha","Lucha","Veneno","Lucha","Lucha","Siniestro","Eléctrico","Dragón","Hielo","Fantasma","Psíquico","Psíquico","Psíquico","Normal","Bicho","Agua"];

        $tipo2=["Veneno","Veneno","Veneno","Fuego","Fuego","Volador","Agua","Agua","Agua","Bicho","Bicho","Volador","Veneno","Veneno","Veneno","Volador","Volador","Volador",
            "Normal","Normal","Volador","Volador","Veneno","Veneno","Eléctrico","Eléctrico","Tierra","Tierra","Veneno","Veneno","Tierra","Veneno","Veneno","Tierra","Hada",
            "Hada","Fuego","Fuego","Hada","Hada","Volador","Volador","Veneno","Veneno","Veneno","Planta","Planta","Veneno","Veneno","Tierra","Tierra","Normal","Normal","Agua",
            "Agua","Lucha","Lucha","Fuego","Fuego","Agua","Agua","Lucha","Psíquico","Psíquico","Psíquico","Lucha","Lucha","Lucha","Veneno","Veneno","Veneno","Veneno","Veneno",
            "Tierra","Tierra","Tierra","Fuego","Fuego","Psíquico","Psíquico","Acero","Acero","Volador","Volador","Volador","Agua","Hielo","Veneno","Veneno","Agua","Hielo",
            "Veneno","Veneno","Veneno","Tierra","Psíquico","Psíquico","Agua","Agua","Eléctrico","Eléctrico","Psíquico","Psíquico","Tierra","Tierra","Lucha","Lucha","Normal",
            "Veneno","Veneno","Roca","Roca","Normal","Planta","Normal","Agua","Agua","Agua","Agua","Agua","Psíquico","Hada","Volador","Psíquico","Eléctrico","Fuego","Bicho",
            "Normal","Agua","Volador","Hielo","Normal","Normal","Agua","Eléctrico","Fuego","Normal","Agua","Agua","Agua","Agua","Volador","Normal","Volador","Volador",
            "Volador","Dragón","Dragón","Volador","Psíquico","Psíquico","Planta","Planta","Planta","Fuego","Fuego","Fuego","Agua","Agua","Agua","Normal","Normal","Volador",
            "Volador","Volador","Volador","Veneno","Veneno","Volador","Eléctrico","Eléctrico","Eléctrico","Hada","Hada","Hada","Volador","Volador","Volador","Eléctrico",
            "Eléctrico","Eléctrico","Planta","Hada","Hada","Roca","Agua","Volador","Volador","Volador","Normal","Planta","Planta","Volador","Tierra","Tierra","Psíquico",
            "Siniestro","Volador","Psíquico","Fantasma","Psíquico","Psíquico","Psíquico","Bicho","Acero","Normal","Volador","Tierra","Hada","Hada","Veneno","Acero","Roca",
            "Lucha","Hielo","Normal","Normal","Fuego","Roca","Tierra","Tierra","Roca","Agua","Agua","Volador","Volador","Volador","Fuego","Fuego","Dragón","Tierra","Tierra",
            "Normal","Normal","Normal","Lucha","Lucha","Psíquico","Eléctrico","Fuego","Normal","Normal","Eléctrico","Fuego","Agua","Tierra","Tierra","Siniestro","Volador",
            "Volador","Planta","Planta","Planta","Planta","Fuego","Lucha","Lucha","Agua","Tierra","Tierra","Siniestro","Siniestro","Normal","Normal","Bicho","Bicho","Volador",
            "Bicho","Veneno","Planta","Planta","Planta","Planta","Siniestro","Siniestro","Volador","Volador","Volador","Volador","Hada","Hada","Hada","Agua","Volador",
            "Planta","Lucha","Normal","Normal","Normal","Tierra","Volador","Fantasma","Normal","Normal","Normal","Lucha","Lucha","Hada","Roca","Normal","Normal","Fantasma",
            "Hada","Roca","Roca","Roca","Psíquico","Psíquico","Eléctrico","Eléctrico","Eléctrico","Eléctrico","Bicho","Bicho","Veneno","Veneno","Veneno","Siniestro",
            "Siniestro","Agua","Agua","Tierra","Tierra","Fuego","Psíquico","Psíquico","Normal","Tierra","Dragón","Dragón","Planta","Siniestro","Volador","Volador","Normal",
            "Veneno","Psíquico","Psíquico","Tierra","Tierra","Agua","Siniestro","Psíquico","Psíquico","Planta","Planta","Bicho","Bicho","Agua","Agua","Normal","Normal",
            "Fantasma","Fantasma","Fantasma","Fantasma","Volador","Psíquico","Siniestro","Psíquico","Hielo","Hielo","Agua","Agua","Agua","Agua","Agua","Agua","Roca","Agua",
            "Dragón","Dragón","Volador","Psíquico","Psíquico","Psíquico","Roca","Hielo","Acero","Psíquico","Psíquico","Agua","Tierra","Volador","Psíquico","Psíquico",
            "Planta","Planta","Tierra","Fuego","Lucha","Lucha","Agua","Agua","Acero","Volador","Volador","Volador","Normal","Agua","Bicho","Bicho","Eléctrico","Eléctrico",
            "Eléctrico","Veneno","Veneno","Roca","Roca","Acero","Acero","Bicho","Planta","Volador","Volador","Volador","Eléctrico","Agua","Agua","Planta","Planta","Agua",
            "Tierra","Normal","Volador","Volador","Normal","Normal","Fantasma","Volador","Normal","Normal","Psíquico","Siniestro","Siniestro","Psíquico","Psíquico","Roca",
            "Hada","Normal","Volador","Siniestro","Tierra","Tierra","Tierra","Normal","Lucha","Acero","Tierra","Tierra","Bicho","Siniestro","Lucha","Lucha","Planta","Agua",
            "Agua","Volador","Hielo","Hielo","Hielo","Acero","Normal","Roca","Planta","Eléctrico","Fuego","Volador","Volador","Planta","Hielo","Volador","Tierra","Normal",
            "Lucha","Acero","Fantasma","Fantasma","Fantasma","Psíquico","Psíquico","Psíquico","Dragón","Dragón","Acero","Normal","Dragón","Psíquico","Agua","Agua","Siniestro",
            "Planta","Normal","Planta","Planta","Planta","Fuego","Lucha","Lucha","Agua","Agua","Agua","Normal","Normal","Normal","Normal","Normal","Siniestro","Siniestro",
            "Planta","Planta","Fuego","Fuego","Agua","Agua","Psíquico","Psíquico","Volador","Volador","Volador","Eléctrico","Eléctrico","Roca","Roca","Roca","Volador",
            "Volador","Tierra","Acero","Normal","Lucha","Lucha","Lucha","Agua","Tierra","Tierra","Lucha","Lucha","Planta","Planta","Planta","Veneno","Veneno","Veneno","Hada",
            "Hada","Planta","Planta","Agua","Siniestro","Siniestro","Siniestro","Fuego","Fuego","Planta","Roca","Roca","Lucha","Lucha","Volador","Fantasma","Fantasma","Roca",
            "Roca","Volador","Volador","Veneno","Veneno","Siniestro","Siniestro","Normal","Normal","Psíquico","Psíquico","Psíquico","Psíquico","Psíquico","Psíquico","Volador",
            "Volador","Hielo","Hielo","Hielo","Planta","Planta","Volador","Bicho","Acero","Veneno","Veneno","Fantasma","Fantasma","Agua","Eléctrico","Eléctrico","Acero",
            "Acero","Acero","Acero","Acero","Eléctrico","Eléctrico","Eléctrico","Psíquico","Psíquico","Fuego","Fuego","Fuego","Dragón","Dragón","Dragón","Hielo","Hielo",
            "Hielo","Bicho","Bicho","Eléctrico","Lucha","Lucha","Dragón","Fantasma","Fantasma","Acero","Acero","Normal","Volador","Volador","Volador","Volador","Fuego",
            "Acero","Dragón","Dragón","Dragón","Fuego","Fuego","Lucha","Lucha","Lucha","Volador","Volador","Fuego","Eléctrico","Volador","Hielo","Lucha","Psíquico","Acero",
            "Planta","Planta","Lucha","Fuego","Fuego","Psíquico","Agua","Agua","Siniestro","Normal","Tierra","Volador","Volador","Volador","Bicho","Bicho","Volador","Normal",
            "Normal","Hada","Hada","Hada","Planta","Planta","Lucha","Siniestro","Normal","Psíquico","Psíquico","Fantasma","Fantasma","Fantasma","Hada","Hada","Hada","Hada",
            "Psíquico","Psíquico","Agua","Agua","Agua","Dragón","Agua","Agua","Normal","Normal","Dragón","Dragón","Hielo","Hielo","Hada","Volador","Hada","Hada","Dragón",
            "Dragón","Dragón","Hada","Planta","Planta","Planta","Planta","Hielo","Hielo","Dragón","Dragón","Hada","Volador","Tierra","Hada","Fantasma","Agua","Volador",
            "Volador","Fantasma","Fuego","Fuego","Siniestro","Agua","Agua","Hada","Volador","Volador","Volador","Normal","Normal","Bicho","Eléctrico","Eléctrico","Lucha",
            "Hielo","Volador","Hada","Hada","Roca","Roca","Agua","Agua","Agua","Tierra","Tierra","Bicho","Bicho","Planta","Planta","Hada","Hada","Fuego","Fuego","Lucha",
            "Lucha","Planta","Planta","Planta","Hada","Psíquico","Lucha","Agua","Agua","Tierra","Tierra","Agua","Normal","Normal","Volador","Normal","Dragón","Acero","Hada",
            "Psíquico","Dragón","Planta","Dragón","Lucha","Lucha","Hada","Hada","Hada","Hada","Psíquico","Psíquico","Acero","Fantasma","Veneno","Lucha","Lucha","Eléctrico",
            "Volador","Acero","Dragón","Psíquico","Hada","Fantasma","Veneno","Dragón","Acero","Fantasma","Eléctrico","Acero","Acero","Agua","Planta","Planta","Planta","Fuego",
            "Fuego","Fuego","Agua","Agua","Agua","Normal","Normal","Volador","Volador","Acero","Bicho","Psíquico","Psíquico","Siniestro","Siniestro","Planta","Planta",
            "Normal","Normal","Agua","Roca","Eléctrico","Eléctrico","Roca","Fuego","Fuego","Dragón","Dragón","Dragón","Tierra","Tierra","Agua","Agua","Agua","Veneno","Veneno",
            "Bicho","Bicho","Lucha","Lucha","Fantasma","Fantasma","Psíquico","Psíquico","Hada","Hada","Hada","Hada","Normal","Acero","Fantasma","Lucha","Psíquico","Fantasma",
            "Hada","Hada","Lucha","Eléctrico","Bicho","Bicho","Roca","Hielo","Normal","Siniestro","Acero","Acero","Dragón","Hielo","Dragón","Hielo","Dragón","Fantasma",
            "Fantasma","Fantasma","Hada","Acero","Lucha","Acero","Dragón","Lucha","Siniestro","Agua","Planta","Eléctrico","Dragón","Hielo","Fantasma","Planta","Hielo",
            "Fantasma","Psíquico","Roca","Fantasma"];


        $ataque_hielo=["Alud","Bola hielo","Carámbano","Chuzos","Colmillo hielo","Crioaliento despiadado","Esquirla helada","Fría acogida","Frío polar","Gigamelodía",
            "Glaceoprisma","Granizo","Lanza glacial","Liofilización","Llama gélida","Martillo hielo","Maxihelada","Mundo gélido","Neblina","Niebla","Nieve polvo",
            "Paisaje nevado","Pirueta helada","Puño hielo","Rayo aurora","Rayo gélido","Rayo hielo","Triple axel","Vaho gélido","Velo aurora","Ventisca","Viento carámbano",
            "Viento hielo"];

        $atack_hada = ["Arrumaco sideral","Beso drenaje","Beso dulce","Brillo magico","Bruma explosiva","Campo de niebla","Cañon floral","Carantoña","Cautivapor",
            "Cerrojo ferico","Choque animico","Ciclon primavera","Colera del guardian","Cura floral","Decoracion","Defensa floral","Encanto", "Feerichoque","Fuerza lunar",
            "Furia natural","Geocontrol","Gigacastigo","Gigacolofon","Luz aniquiladora","Luz lunar","Maxiestela","Niebla aromática","Ojitos tiernos","Somanta amistosa",
            "Sylveotornado","Truco defensa","Viento feérico","Voz cautivadora"];

        $ataque_fuego = ["Anillo ígneo","Ascuas","Balón ígneo","Bomba ígnea","Cabeza sorpresa","Calcinación","Canto ardiente","Cañon armadura","Colmillo ígneo",
            "Coraza trampa","Danza llama","Día soleado","Envidia ardiente","Envite ígneo","Erupción de ira","Espada lamento","Estallido","Flarembestida","Fuego fatuo",
            "Fuego sagrado","Gigacienfuegos","Gigaesfera ígnea","Gigallamarada","Giro fuego","Golpe calor","Hecatombe pírica","Humareda","Infierno","Lanzallamas",
            "Látigo ígneo","Llama azul","Llama embrujada","Llama final","Llama fusión","Llamarada","Lluvia ígnea","Maxignición","Nitrocarga","Onda ígnea","Patada ígnea",
            "Pirochoque","Pirotecnia","Puño fuego","Rueda fuego","Sofoco","V de fuego","Voto fuego"];

        $ataque_fantasma = ["Aluvión de flechas sombrías","Bola sombra","Constelación robaalmas","Deflagración lunar","Garra umbría","Gigaaparición","Golpe fantasma",
            "Golpe umbrío","Halloween","Homenaje póstumo","Hueso sombrío","Impresionar","Infortunio","Lengüetazo","Maldición","Marcha espectral","Maxiespectro",
            "Mismo destino","Orbes espectro","Pesadilla","Poltergeist","Presa espectral","Puntada sombría","Puño furia","Puño sombra","Rabia","Rayo confuso","Rayo umbrío",
            "Rencor","Rencor reprimido","Robasombra","Sombra vil","Tinieblas","Viento aciago"];

        $ataque_electrico = ["Alto voltaje","Amplificador","Ataque fulgor","Aura magnética","Bola voltio","Campo eléctrico","Carga","Carga parábola","Chispa","Chispazo",
            "Colmillo rayo","Cortina plasma","Electormenta","Electrificación","Electrocañón","Electroderrape","Electrojaula","Electropalmas","Electropico","Electropunzada",
            "Electrotela","Gigadescarga","Gigarrayo fulminante","Gigatronada","Gigavoltio destructor","Impactrueno","Joltioparálisis","Levitón","Maxitormenta",
            "Moflete estático","Onda anómala","Onda trueno","Onda voltio","Pikatormenta","Pikaturbo","Pikavoltio letal","Placaje eléctrico","Puño trueno","Puños plasma",
            "Rayo","Rayo carga","Rayo fusión","Rueda aural","Surfeo galvánico","Trueno","Voltio cruel","Voltiocambio"];

        $ataque_dragon = ["Asalto espadón","Cañón Dinamax","Carga dragón","Ciclón","Cola dragón","Cometa draco","Corte vacío","Danza dragón","Distorsión",
            "Dracoaliento devastador","Dracoenergía","Dracoflechas","Dragoaliento","Enfado","Estruendo escama","Estruendo implacable","Fragor escamas","Furia dragón",
            "Garra dragón","Gigadesgaste","Golpe bis","Martillo dragón","Maxidraco","Núcleo castigo","Oído cocina","Pulso dragón","Ráfaga escamas","Rayo infinito",
            "Vasto impacto"];

        $ataque_bicho = ["A defender","Acoso","Aguijón letal","Al ataque","Auxilio","Bola de polen","Brinco","Chupavidas","Corte furia","Danza aleteo","Disparo demora",
            "Doble ataque","Escaramuza","Estoicismo","Gigaestupor","Golpe rastrero","Guadaña sedosa","Ida y vuelta","Luminicola","Maxinsecto","Megacuerno","Picadura",
            "Pin misil","Plancha","Polvo explosivo","Polvo ira","Rayo señal","Red viscosa","Rodillo de púas","Telaraña","Telatrampa","Tijera X","Viento plata","Zumbido"];

        $ataque_agua = ["Acua aro","Acua cola","Acua jet","Agua fría","Agua lodosa","Aria burbuja","Azote torrencial","Branquibocado","Buceo","Burbuja","Cascada",
            "Chorro de vapor","Concha filo","Danza acuática","Danza lluvia","Disparo certero","Empapar","Envite acuático","Escaldar","Gigacañonazo","Gigadisparo",
            "Gigaespuma","Gigagolpe fluido","Gigatrampa rocas","Gota vital","Hidroariete","Hidrobomba","Hidrocañón","Hidrochorro","Hidropulso","Hidrovapor",
            "Hidrovórtice abisal","Martillazo","Maxichorro","Pistola agua","Pulpocañón","Pulso primigenio","Puño jet","Rayo burbuja","Refugio","Salmuera","Salpicar",
            "Salpikasurf","Shuriken de agua","Sinfonía de la diva marina","Surf","Tajo acuático","Tenaza","Torbellino","Triple inmersión","Vapodrenaje","Viraje","Voto agua"];

        $ataque_acero = ["Ala de acero","Aligerar","Allanador férreo","Anclaje","Bomba imán","Cabeza de hierro","Cambio de marcha","Cola férrea","Cuerno certero",
            "Cuerpo pesado","Defensa férrea","Deseo oculto","Disparo espejo","Eco metálico","Embate supremo","Embestida solar","Escudo real","Ferropuño doble",
            "Fiebre dorada","Foco resplandor","Garra metal","Gigafundido","Gigatrampa acero","Giro bola","Hélice trepanadora","Martillo colosal","Maximetal","Metaláser",
            "Meteoimpacto","Piñón auxiliar","Puño bala","Puño meteoro","Quemarrueda","Represión metal","Retracción","Rueda doble","Tajo supremo"];

        $ataque_lucha = ["A bocajarro","Anticipo","Asalto estelar","Bastión final","Contraataque","Corpulencia","Danza triunfal","Demolición","Desquite","Detección",
            "Doble patada","Empujón","Escudo tatami","Esfera aural","Espabila","Espada santa","Fuerza bruta","Gancho alto","Gigapuñición","Golpe kárate","Golpe roca",
            "Inversión","Llave corsé","Llave giro","Llave vital","Machada","Maxipuño","Motivación","Nitrochoque","Octopresa","Onda certera","Onda vacío","Palmeo",
            "Patada baja","Patada giro","Patada hacha","Patada relámpago","Patada salto","Patada salto alta","Plancha corporal","Plancha voladora","Pugnachoque",
            "Puntapié","Puño certero","Puño dinámico","Puño drenaje","Puño incremento","Ráfaga demoledora","Sable místico","Sacrificio","Sísmico","Sumisión","Tajo cruzado",
            "Triple flecha","Triple patada","Ultrapuño"];

        $ataque_normal = ["Acupresión","Adaptación","Afilar","Agarre","Agarrón","Aguante","Aguzar","Alboroto","Alivio","Amago","Antojo","Anulación","Arañazo","Ariete",
            "Arrojo intempestivo","As oculto","Atadura","Ataque furia","Ataque rápido","Atiborramiento","Atizar","Atracción","Aullido","Autodestrucción","Autosugestión",
            "Autotomía","Avivar","Ayuda","Azote","Batido","Beso amoroso","Bloqueo","Bomba huevo","Bomba sónica","Bombardeo","Bostezo","Cabezazo","Camaradería","Cambiapoder",
            "Cambio de cancha","Camuflaje","Canon","Canto","Canto arcaico","Canto mortal","Cara susto","Carrera arrolladora","Cascabel cura","Cede paso","Celebración",
            "Chirrido","Clavo cañón","Clemencia","Clonatipo","Confidencia","Conjuro","Constricción","Contoneo","Conversión","Conversión2","Copión","Cornada","Corte",
            "Cosquillas","Cuchillada","Danza amiga","Danza caos","Danza despertar","Danza espada","Daño secreto","Decalcomanía","Derribo","Desarrollo","Deseo","Deslome",
            "Deslumbrar","Destello","Destructor","Día de pago","Divide dolor","Doble bofetón","Doble equipo","Doble filo","Doble golpe","Don natural","Dulce aroma",
            "Eco voz","Eevimpacto","Escupir","Esfuerzo","Esquema","Estímulo","Estruendo","Estrujón","Explosión","Falso tortazo","Fijar blanco","Foco","Foco energía",
            "Fortaleza","Frustración","Fuerza","Furia","Furia taurina","Garra brutal","Gigaimpacto","Gigamonedas","Gigarreciclaje","Gigaternura","Giro rápido","Golpe cabeza",
            "Golpe cuerpo","Golpes furia","Gruñido","Guardia baja","Guillotina","Hipercolmillo","Hiperrayo","Hipertaladro","Hora del té","Imagen","Látigo","Limpieza general",
            "Mal de ojo","Malicioso","Manos juntas","Maxiataque","Maxibarrera","Megapatada","Megapuño","Meteorobola","Meteoros","Metrónomo","Mimético","Multiataque",
            "Novena potencia","Ofrenda","Ojos llorosos","Onda simple","Otra vez","Ovocuración","Paga extra","Pantalla de humo","Perforador","Pisotón","Placaje",
            "Plegaria vital","Plumerazo","Poder oculto","Presente","Profecía","Proliferación","Protección","Pulso de campo","Puño cometa","Puño mareo","Rastreo","Reciclaje",
            "Recuperación","Reducción","Refuerzo","Relajo","Relevo","Remolino","Represalia","Reserva","Restricción","Retribución","Rizo defensa","Rompecoraza","Ronquido",
            "Rugido","Rugido de guerra","Salpicadura","Saña","Seducción","Sentencia","Señuelo","Sol matinal","Sonámbulo","Sorpresa","Superdiente","Supersónico","Sustituto",
            "Tambor","Tecno shock","Telépata","Teraexplosión","Tragar","Transformación","Treparrocas","Triataque","Última baza","Velo sagrado","Velocidad extrema","Venganza",
            "Viento cortante","Vozarrón","Yo primero"];

        $ataque_planta = ["Abatidoras","Abrecaminos","Absorbefuerza","Absorber","Ácido málico","Aromaterapia","Arraigo","Asta drenaje","Barrera espinosa","Batería asalto",
            "Bomba germen","Brazo pincho","Campo de hierba","Cepo","Ciclón de hojas","Clorofiláser","Condena silvana","Cuchilla solar","Cura selvática","Danza pétalo",
            "Drenadoras","Energibola","Espora","Esporagodón","Extracto picante","Fitoimpulso","Follaje","Fuerza G","Fulgor semilla","Gigacorrosión","Gigadrenado","Gigalianas",
            "Giganéctar","Gigarredoble","Hierba lazo","Hoja afilada","Hoja aguda","Hoja mágica","Latigazo","Látigo cepa","Leafitobombas","Lluevehojas","Maxiflora","Mazazo",
            "Megaagotar","Megatón floral","Paralizador","Patada tropical","Planta feroz","Punzada rama","Rayo solar","Rizo algodón","Semilladora","Silbato","Síntesis",
            "Somnífero","Tormenta floral","Truco floral","Voto planta"];

        $ataque_psiquico = ["Agilidad","Ala aural","Amnesia","Anticura","Arrumaco","Asalto barrera","Bálsamo osado","Barrera","Bola neblina","Cabezazo zen","Cambiaalmas",
            "Cambiadefensa","Cambiafuerza","Cambiavelocidad","Cambio de banda","Campo psíquico","Capa mágica","Comesueños","Confusión","Conjuro funesto","Danza lunar",
            "Descanso","Deseo cura","Disruptor psíquico","Espacio raro","Espeaura","Fotocolisión","Fotodestrucción apocalíptica","Géiser fotónico","Gigabóveda","Gran ojo",
            "Gravedad","Hipnosis","Imitación","Intercambio","Isofuerza","Isoguardia","Kinético","Láser doble","Láser prisma","Mandato","Manto espejo","Masa cósmica",
            "Maxionda","Meditación","Mirada heladora","Onda mental","Pantalla de luz","Paranormal","Paso dimensional","Paz mental","Plegaria lunar","Poder místico",
            "Poder reserva","Polvo mágico","Premonición","Psicoataque","Psicocambio","Psicocarga","Psicocolmillo","Psicocorte","Psicohojas","Psicoonda","Psicorrayo",
            "Psíquico","Pulso cura","Reflejo","Resplandor","Sellar","Sincrorruido","Supernova original","Telequinesis","Teletransporte","Truco","Truco fuerza","Vasta fuerza",
            "Zona extraña","Zona mágica"];

        $ataque_roca = ["Alquitranazo","Antiaéreo","Aplastamiento gigalítico","Avalancha","Gigarroca ígnea","Hachazo pétreo","Joya de luz","Lanzarrocas","Maxilito",
            "Pedrada","Poder pasado","Pulimento","Rayo meteórico","Roca afilada","Roca veloz","Rodar","Romperrocas","Salazón","Tempestad rocosa","Testarazo",
            "Tormenta de arena","Tormenta de diamantes","Trampa rocas","Tumba rocas","Vasta guardia"];

        $ataque_siniestro = ["Afilagarras","Agujero negro aniquilador","Alarido","Brecha negra","Buena baza","Calamidad","Camelo","Castigo","Cerco dimensión","Chulería",
            "Desahogo","Desarme","Embargo","Finta","Furia candente","Genufendiente","Gigagolpe brusco","Gigasopor","Giro vil","Golpe bajo","Golpe mordaza","Golpe oscuro",
            "Hiperplancha oscura","Irreverencia","Juego sucio","Ladrón","Lanzamiento","Lariat oscuro","Legado","Llanto falso","Maquinación","Maxisombra","Mofa","Mordisco",
            "Obstrucción","Ominochoque","Paliza","Persecución","Presa maxilar","Pulso noche","Pulso umbrío","Resarcimiento","Reversión","Robo","Tajo metralla","Tajo umbrío",
            "Tormento","Trapicheo","Triturar","Última palabra","Último lugar","Umbreozona","Vendetta"];

        $ataque_tierra = ["Arenas ardientes","Arremetida","Ataque arena","Ataque óseo","Barrena telúrica","Bofetón lodo","Bomba fango","Bucle arena","Chapoteo lodo",
            "Disparo lodo","Excavar","Fertilizante","Filo del abismo","Fisura","Fuerza equina","Fuerza telúrica","Gigapolvareda","Hueso palo","Huesomerang","Magnitud",
            "Maxitemblor","Mil flechas","Mil temblores","Pataleta","Puas","Recogearena","Simun de arena","Taladradora","Terratemblor","Terremoto","Tierra viva"];

        $ataque_veneno = ["Acido","Armadura ácida","Bilis","Bomba ácida","Bomba lodo","Búnker","Carga tóxica","Cola veneno","Colmillo veneno","Diluvio corrosivo","Enrosque",
            "Eructo","Garra nociva","Gas corrosivo","Gas venenoso","Gigapestilencia","Giro mortífero","Hilo venenoso","Lanzamugre","Maxiácido","Mil púas tóxicas",
            "Moluscañón","Niebla clara","Onda tóxica","Picotazo veneno","Polución","Polvo veneno","Ponzochoque","Púas tóxicas","Purificación","Puya nociva","Residuos",
            "Toxico","Trampa venenosa","Veneno X"];

        $ataque_volador = ["Acrobata","Aerochorro","Aire afilado","Ala bis","Ala mortífera","Ascenso draco","Ataque aéreo","Ataque ala","Bote","Caída libre","Cháchara",
            "Danza pluma","Despejar","Espejo","Gigahuracán","Golpe aéreo","Maxiciclón","Pájaro osado","Picado supersónico","Pico cañón","Pico taladro","Picotazo","Picoteo",
            "Pikapicado","Respiro","Tajo aéreo","Tornado","Vendaval","Vendaval gélido","Viento afín","Vuelo"];
